In [2]:
import numpy as np

In [ ]:
# arr = np.array([1, 2, 3, 4, 5])
# print(arr)

arr = np.array(range(10))
print(arr)

In [ ]:
a = np.zeros((4,5), dtype=int) # Create a 4x5 array filled with zeros
print(a)

b = np.ones((3,4), dtype=int) # Create a 3x4 array filled with ones
print(b)

c = np.full((2,3), 17, dtype=int)   # Create a 2D array filled with 17
print(c)

d = np.eye(3, dtype=int) # Identity matrix
print(d)

e = np.random.random((3,2)) # Create a 2x2 array with random floats
print(e)

f = np.arange(0, 25, 5) # Create an array with values from 10 to 25 with a step of 5
print(f)    

g = np.linspace(0, 2, 9) # Create an array with 9 values evenly spaced between 0 and 2      
print(g)

In [ ]:
# 1D array
one = np.array([1, 2, 3, 4, 5])
print(one)  

In [ ]:
d = np.eye(3,3, dtype=int) #create a 3x3 identity matrix
print(d)

In [2]:
# 2 D array
two = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(two)
print(two[1,2]) # Accessing an element in a 2D array
print(two[1])  # Accessing a row in a 2D array
print(two[:, 1])  # Accessing a column in a 2D array
print(two[:, :])  # Accessing a column in a 2D array
print(two[1:2])  # Slicing a 2D array
print(two[0:2, 0:2]) # Slicing a 2D array with specific rows and columns

[[1 2 3]
 [4 5 6]
 [7 8 9]]
6
[4 5 6]
[2 5 8]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[4 5 6]]
[[1 2]
 [4 5]]


In [1]:
# 3 D array
import numpy as np
three = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(three)
print(three[0, 1, 2])  # Accessing an element in a 3D array
print(three[0, 1])  # Accessing a 2D slice in a 3D array
# print(three[:, 1])  # Accessing a 2D slice in a 3D array
print(three[0, :, 1])  # Accessing a column in a 3D array
print(three[0:1, 0:2, 0:2]) # Slicing a 3D array with specific dimensions

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
6
[4 5 6]
[2 5]
[[[1 2]
  [4 5]]]


In [19]:
t = np.array([[[1,2,3],[4,5,6]],[[6,7,8],[10,11,12]],[[13,14,15],[16,17,18]]])
print(t.shape)
print(t.ndim)
print(t.size)
print(t.reshape(-1,9))
print(t.ravel())
print(t.flatten())

(3, 2, 3)
3
18
[[ 1  2  3  4  5  6  6  7  8]
 [10 11 12 13 14 15 16 17 18]]
[ 1  2  3  4  5  6  6  7  8 10 11 12 13 14 15 16 17 18]
[ 1  2  3  4  5  6  6  7  8 10 11 12 13 14 15 16 17 18]


In [5]:
a =4587
count=0
while a!= 0:
    a = a // 10
    count += 1 
print(count)  # Count the number of digits in a number

print(len(str(4587)))  # Count the number of digits in a number using string conversion

4
4


In [ ]:
a = np.array([[25, 50, 75, 100],[34,40, 60, 80],[15, 27, 37, 44],[12, 18, 24, 30],[5, 10, 15, 20],[23, 45, 67, 89]])
print(a)
# print(a[2])  # Accessing a row in a 2D array
# print(a[:,3]) # Accessing a 3rd column in a 2D array
# # print(a[:,-1]) # Accessing the last column in a 2D array
# print(a[:,::-1]) # Accessing all rows and reversing the columns
# print(a[1:3, 1:3])  # Slicing a 2D array with specific rows and columns
a[:,-2] = a[:,-2] * 2  # Doubling the second last column
a[-2] = a[-2]*2 # Doubling the second last row
print("A\n", a)
a[a<25] = 28
print("A\n", a)  # Replacing all elements less than 25 with 28  
print("A \n", a.ravel())  # Flattening the array to 1D
print("A \n", a.reshape(6, 4))  # Reshaping the array to 6 rows and 4 columns


In [ ]:
import numpy as np
def create_matrix(name):
    try:
        rows=int(input(f"Enter a no of rows for {name}"))
        cols = int(input(f"Enter a no of columns for {name}"))
        print(f"Enter the matrix of {name}")
        matrix=[]
        for x in range(rows):
            row = []
            for y in range(cols):
                val=int(input(f"The index of {x+1},{y+1}"))
                row.append(val)
            matrix.append(row)
        return np.array(matrix)
    except ValueError:
        print("Enter only Numeric value")
        return None
      
def add(a,b):
    if a.shape == b.shape:
        return a + b
    else:
        return "Error: Matrices must have the same dimensions."
def sub(a,b):
    if a.shape == b.shape:
        return a - b
    else:
        return "Error: Matrices must have the same dimensions."
def multiplication(a, b):
    try:
        return np.dot(a, b)
    except ValueError:
        return "Error: Cannot multiply these matrices."

def division(a, num):
    try:
        return a / num
    except ZeroDivisionError:
        return "Error: Division by zero."


mat_A=create_matrix("A")
print(mat_A)
mat_B=create_matrix("B")
print(mat_B)

while True:
    print("Enter your choice from 1 to 5")
    print("1. Addition")
    print("2. Subtraction")
    print("3. Multiplication")
    print("4. Division of Matrix A by a number")
    print("5. Exit")

    try:
        choice = int(input("Enter your choice"))
        if choice ==1:
            print("Addition",add(mat_A,mat_B))
        elif choice==2:
            print("Sub",sub(mat_A,mat_B))
        elif choice==3:
            print("Multiply",multiplication(mat_A,mat_B))
        elif choice==4:
            num = int(input("enter a no to divide"))
            print("Divide",division(mat_A,num))
        elif choice==5:
            print("Thank you! Exiting the calculator.")
            break
        else:
            print("Invalid choice")
    except ValueError:
        print("Enter the valid input form 1 to 5 ")

Enter the matrix of A
Enter only Numeric value
None
Enter only Numeric value
None
Enter your choice from 1 to 5
1. Addition
2. Subtraction
3. Multiplication
4. Division of Matrix A by a number
5. Exit
Thank you! Exiting the calculator.


In [1]:
matrix = []
for x in range(4):
    matrix.append([])
    # print(matrix)
    for y in range(4):
        matrix[x].append(x + y)
        # print(matrix[x])
    print("Matrix from loop:\n", matrix)

Matrix from loop:
 [[0, 1, 2, 3]]
Matrix from loop:
 [[0, 1, 2, 3], [1, 2, 3, 4]]
Matrix from loop:
 [[0, 1, 2, 3], [1, 2, 3, 4], [2, 3, 4, 5]]
Matrix from loop:
 [[0, 1, 2, 3], [1, 2, 3, 4], [2, 3, 4, 5], [3, 4, 5, 6]]


In [ ]:
matrix = []
for x in range(4):
    row = []
    for y in range(4):
        val = x + y
        row.append(val)
    matrix.append(row)    
print("Matrix from loop:\n", matrix)
print(np.array(matrix))

Matrix from loop:
 [[0, 1, 2, 3]]
Matrix from loop:
 [[0, 1, 2, 3], [1, 2, 3, 4]]
Matrix from loop:
 [[0, 1, 2, 3], [1, 2, 3, 4], [2, 3, 4, 5]]
Matrix from loop:
 [[0, 1, 2, 3], [1, 2, 3, 4], [2, 3, 4, 5], [3, 4, 5, 6]]
[[0 1 2 3]
 [1 2 3 4]
 [2 3 4 5]
 [3 4 5 6]]
