Numpy Arithmetic Operations

In [1]:
import numpy as np

In [2]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[2,3,4],[6,7,8]])
print(a + b)

[[ 3  5  7]
 [10 12 14]]


In [3]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[2,3,4],[6,7,8]])
print(a*b)

[[ 2  6 12]
 [24 35 48]]


In [4]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[2,3,4],[6,7,8]])
print(a/b)

[[0.5        0.66666667 0.75      ]
 [0.66666667 0.71428571 0.75      ]]


In [ ]:
#Broadcast Numpy Arithmetic Operations
a = np.array([1,2,3])
b = np.array([[2,3,4],[6,7,8]])
print(a + b)

print(b.shape)
print(b.ndim)
print(b.size)
a.shape

[[ 3  5  7]
 [ 7  9 11]]
(2, 3)
2
6


(3,)

Indexing, Slicing and Reshaping Operations

In [6]:
#1d array
a = np.array([1,2,3,4,5,6])
print(a[3])

4


In [7]:
#2d array
b = np.array([[2,3,4],[6,7,8]])
print(b[0,1])
print(b[1,1])

3
7


In [8]:
#3d array           
ar = np.array([[[1,2,3,],[4,5,6]],[[7,8,9],[9,10,11]]])
print(ar[1,0,2])
print(ar[0,0,2])
print(ar[1,1,0])
print(ar[0,1,1])

9
3
9
5


In [ ]:
a = np.array([1,2,3,4,5,6,7,8,9])
a = a.reshape(3,3)
print(a)    

In [10]:
'''flatten() (Always returns a new copy)
Always returns a copy of the array.

Modifying the returned array does not affect the original array.

Uses more memory because a new array is created.'''

b = np.array([[2,3,4],[6,7,8]])
print(b.flatten())

[2 3 4 6 7 8]


In [11]:
'''' ravel() (Memory-efficient, returns a view when possible)
Returns a view (not a copy) of the original array when possible.

If you modify the returned array, it may affect the original array.

Faster and more memory-efficient.'''''

b = np.array([[2,3,4],[6,7,8]])
print(b.ravel())

[2 3 4 6 7 8]


In [9]:
a = np.array([1,2,3,4,5,6,7,8,9])
print(a[2:5])

[3 4 5]


In [12]:
b = np.array([[2,3,4],[6,7,8]])
print(b[1, 1:2])
print(b[0, 0:2])

[7]
[2 3]


In [13]:
ar = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[9,10,11]]])
print(ar[1,1,0:2])
print(ar[1,0,0:2])
print(ar[0,0,0:2])
print(ar[0,1,0:2])
print(ar[1,1,::-1])
print(ar[1,0,::-1])

[ 9 10]
[7 8]
[1 2]
[4 5]
[11 10  9]
[9 8 7]


In [14]:
ar = np.array([[[1,2,3],[4,5,6],[9,10,11]],[[7,8,9],[9,10,11],[1,2,3]]])
print(ar[1,2,0:2])

[1 2]


In [15]:
ar = np.array([[[1,2,3],[4,5,6],[9,10,11]],[[7,8,9],[9,10,11],[1,2,3]],[[12,13,14],[15,16,17],[18,19,20]]])
print(ar[2,2,0:2])

[18 19]


In [16]:
ar = np.array([[[1,2,3],[4,5,6],[9,10,11]],[[7,8,9],[9,10,11],[1,2,3]],[[12,13,14],[15,16,17],[18,19,20]]])
print(ar.flatten())

[ 1  2  3  4  5  6  9 10 11  7  8  9  9 10 11  1  2  3 12 13 14 15 16 17
 18 19 20]


In [ ]:
import numpy as np

# 1. Create a (6, 4) NumPy array representing sales (in thousands)
sales = np.array([
    [55, 62, 70, 58],
    [48, 75, 80, 65],
    [60, 82, 78, 70],
    [45, 58, 62, 50],
    [68, 72, 74, 69],
    [50, 55, 60, 53]
])

# 2. Find the sales data for the 3rd shop
shop_3_sales = sales[2]
print("Sales for the 3rd shop:", shop_3_sales)

# 3. Get the sales for all shops in the last quarter
last_quarter_sales = sales[:, -1]
print("Sales in the last quarter:", last_quarter_sales)

# 4. Increase all sales in the first quarter by 10%
sales[:, 0] = sales[:, 0] * 1.10  # Increase first column by 10%
print("Updated sales with 10% increase in Q1:")
print(sales)

# 5. If any sales value is less than 50, change it to 50
sales[sales < 50] = 50
print("Updated sales with minimum value 50:")
print(sales)

# 6. Convert the array into a single-column format
sales_column = sales.reshape(-1, 1)
print("Sales in single-column format:")
print(sales_column) 

# 7. Reshape it back to its original (6, 4) format
sales_reshaped = sales_column.reshape(6, 4)
print("Reshaped back to original form:")
print(sales_reshaped)
