In [1]:
import numpy as np

Mean, Median, Mode

In [2]:
a = np.array([11,20,13,40,15,61,17,81,19])
mean_var = np.mean(a)
print(mean_var)

30.77777777777778


In [3]:
a = np.array([11,20,13,40,15,61,17,81,19])
median_var = np.median(a)
print(median_var)

19.0


In [4]:
from scipy import stats
a1 = np.array([11,20,13,40,15,61,17,81,19,20,20,20,20,20,20])
mode_var = stats.mode(a1, keepdims=True)
print(mode_var.mode[0])
print(mode_var.count[0])
print(mode_var)

20
7
ModeResult(mode=array([20]), count=array([7]))


Variance, Standard deviation, Covariance, Correlation

In [5]:
a= np.array([10,20,30,40,50])
variance=np.var(a)
std_dev = np.std(a)
print(variance)
print(std_dev)

200.0
14.142135623730951


In [6]:
x =np.array([60, 70, 80, 90, 100]) 
y = np.array([65, 68, 85, 95, 105])
covariance = np.cov(x,y)
correlation= np.corrcoef(x,y)
print(covariance)
print(correlation)

[[250.  267.5]
 [267.5 294.8]]
[[1.         0.98534891]
 [0.98534891 1.        ]]


Range

In [7]:
x = np.array([60, 70, 80, 90, 100])
range = np.ptp(x)
print(range)

40


Matrix Arithmetic Operation and Linear Algebra Equation


In [ ]:
a= np.array([[1,2,3],[4,5,6]])
b= np.array([[7,8,9],[10,11,12]])
print("A\n",a)
print("B \n",b)
print(a+b)
print(a-b)
print(a*b)

In [3]:
a= np.array([[1,2],[4,56]])
b= np.array([[7,8],[10,12]])
print('A \n',a)
print('B \n',b)
c = np.dot(a,b)
d = a @ b
print('C \n',c)
print('D \n',d)

A 
 [[ 1  2]
 [ 4 56]]
B 
 [[ 7  8]
 [10 12]]
C 
 [[ 27  32]
 [588 704]]
D 
 [[ 27  32]
 [588 704]]


In [4]:
t = a.T

print("Transpose of A \n",t)

Transpose of A 
 [[ 1  4]
 [ 2 56]]


In [6]:
a= np.array([[1,2,3,5],[4,5,6,8]])

b = a.T

print("A \n",b)

A 
 [[1 4]
 [2 5]
 [3 6]
 [5 8]]


In [12]:
a= np.array([[1,2],[4,5]])
Determinant = np.linalg.det(a)
print("Determinant \n",Determinant)

Determinant 
 -2.9999999999999996


In [10]:
a= np.array([[1,2],[4,56]])
Inverse = np.linalg.inv(a)
print("Inverse \n",Inverse)

Inverse 
 [[ 1.16666667 -0.04166667]
 [-0.08333333  0.02083333]]


In [11]:
a= np.array([[1,2],[4,56]])
b = np.array([1,2])
Equation = np.linalg.solve(a,b)
print("Equation \n",Equation)

Equation 
 [ 1.08333333 -0.04166667]


In [3]:
def gcd(a,b,c):
    while b!=0:
        a, b = b, a % b
    while c!=0:
        a, c = c, a % c
    return a

print("GCD of 20 and 30 is", gcd(20, 30, 56))

GCD of 20 and 30 is 2


In [18]:
# LCM 
def gcd(a,b):
    while b!=0:
        a,b = b,a%b
    return a
def lcm(a,b):
    return (a*b)//gcd(a,b)

a=12
b=18
print(f"The GCD is  and LCM is {lcm(a,b)}")
print(f"The GCD is {gcd(a,b)} and LCM is {lcm(a,b)}")

The GCD is  and LCM is 36
The GCD is 6 and LCM is 36
