In [3]:
import numpy as np

In [ ]:
arr1 = np.array([1, 2, 3, 4]) # Create a NumPy array

In [ ]:
a = np.array(range(10)) # Create an array with values from 0 to 9
print(a)

In [ ]:
arr1

In [ ]:
a = np.zeros((4,5), dtype=int) # Create a 4x5 array filled with zeros
print(a)

b = np.ones((3,4), dtype=int) # Create a 3x4 array filled with ones
print(b)

c = np.full((2,3), 17, dtype=int)   # Create a 2D array filled with 17
print(c)

d = np.eye(3, dtype=int) # Identity matrix
print(d)

e = np.random.random((3,2)) # Create a 2x3 array with random floats
print(e)

f = np.arange(0, 25, 5) # Create an array with values from 10 to 25 with a step of 5
print(f)    

g = np.linspace(0, 2, 9) # Create an array with 9 values evenly spaced between 0 and 2      
print(g)

h = np.eye(3,2, dtype=int) # Identity matrix
print(h)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
[[17 17 17]
 [17 17 17]]
[[1 0 0]
 [0 1 0]
 [0 0 1]]
[[0.44505618 0.24384923]
 [0.53022605 0.69565677]
 [0.0816105  0.59976172]]
[ 0  5 10 15 20]
[0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ]
[[1 0]
 [0 1]
 [0 0]]


In [ ]:
#1d array
arr = np.array([1,2,3,4])
print(arr)

In [ ]:
#2d array
arr = np.array([[1,2,3,4],[4,5,6,7]])

print(arr)

In [ ]:
#2d array
arr = np.array([[1,2,3,4],[4,5,6,7],[7,8,9,10]])

print(arr)

In [ ]:
#3d array
arr = np.array([[[1,2,3,],[4,5,6]],[[7,8,9],[9,10,11]]])

print(arr)

In [ ]:
arr = np.random.random((2,1,3,3,3))

print(arr)

In [4]:
arr2 = np.array([[[1,2,3,],[4,5,6]],[[7,8,9],[9,10,11]]])
print(arr2)

print(arr2.shape)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [ 9 10 11]]]
(2, 2, 3)


In [5]:
arr2.ndim

3

In [6]:
print(arr2.size)

print(arr2.dtype)

12
int64


In [7]:
arr3=np.zeros((2,3,3))  
print(arr3)
print(arr3.dtype)
print(arr3.shape)
print(arr3.ndim)
print(arr3.size)

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]
float64
(2, 3, 3)
3
18


In [1]:
import numpy as np
arr4=np.array(range(10,52,2))

print(arr4)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


In [2]:
arr4 = np.arange(10, 52, 2) 
print(arr4)


[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


In [3]:
arr4 = np.arange(10) 
print(arr4)


[0 1 2 3 4 5 6 7 8 9]


In [ ]:
a = np.array(range(10))
a

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])