In [34]:
#Missing Number Finder
def no(num):
    n = len(num)+1
    a = set(range(1, n+1))
    b = set(num)
    c = a - b
    return c.pop() if c else None
num=[4, 2, 3, 5]
print(no(num))  # Output: 4

1


In [33]:
n = [2,5,15,21,56,27]  # This line seems to be a leftover and not used in the function
min = n[0]
max = n[0]
for i in n:
    if i < min:
        min = i
    elif i > max:
        max = i

print("Min:", min)  # Output: Min: 2
print("Max:", max)  # Output: Max: 56

Min: 2
Max: 56


In [26]:
n = int(input("Enter a number: "))
p =0
for i in range(1, n):
    if n % i == 0:
        p += i
if p == n:
    print(n, "is a perfect number") 
else:
    print(n, "is not a perfect number")    

28 is a perfect number


In [39]:
text = "cat bat elephant dog"
a = text.split()
b = a[0]
for i in a:
    if len(i) > len(b):
        b = i

print("largest word:", b)  # Output: largest word: elephant


largest word: elephant


In [43]:
# Reversing a string without using built-in functions
def reverse(s):
    rev=""
    for i in s:
        rev = i + rev   
    return rev  
s = input("Enter a string: ")
print("Reversed string:", reverse(s)) 
if s == reverse(s):
    print("The string is a palindrome") 
else:
    print("The string is not a palindrome") 

Reversed string: olleh
The string is not a palindrome


In [ ]:
n = int(input("Enter a number: "))
p = 0   
while n > 0: 
    r = n % 10
    p = p * 10 + r
    n = n // 10
print("Reversed number:", p)  # Output: Reversed number: 54321

Reversed number: 6
Reversed number: 63
Reversed number: 635


In [ ]:
def factorial(n):
    if n == 0 or n == 1:
        return 1
    else:
        return n * factorial(n - 1)
    
n = int(input("Enter a number: "))
print("Factorial of", n, "is", factorial(n))  # Output: Factorial of 5 is 120

Factorial of 5 is 120


In [3]:
import numpy as np
matrix = []
for i in range(4):
    matrix.append([])
    for j in range(4):
        val = i+j
        matrix[i].append(val)

print("Matrix:",matrix)
print(np.array(matrix))

Matrix: [[0, 1, 2, 3], [1, 2, 3, 4], [2, 3, 4, 5], [3, 4, 5, 6]]
[[0 1 2 3]
 [1 2 3 4]
 [2 3 4 5]
 [3 4 5 6]]


In [36]:
matrix = []
for i in range(4):
    row = []
    for j in range(4):
        # val = i + j
        row.append(j)
    matrix.append(row)

print(matrix)

[[0, 1, 2, 3], [0, 1, 2, 3], [0, 1, 2, 3], [0, 1, 2, 3]]


In [35]:
# LCM and GCD calculation
def gcd(a,b):
    while b!=0:
        a,b = b,a%b
    return a
def lcm(a,b):
    return (a*b)//gcd(a,b)

a=12
b=18
print(f"The GCD is {gcd(a,b)} and LCM is {lcm(a,b)}")

The GCD is 6 and LCM is 36


In [5]:
a = int(input("Enter a number: "))
count = 0
while a != 0:
    a = a // 10
    count += 1
print("Number of digits:", count)  # Output: Number of digits: 3

Number of digits: 3


In [23]:
a=0
while a<5:
    j=0
    while j<=a:
        print("*", end="")
        j += 1
    print()  # Move to the next line after printing stars
    a +=1

*
**
***
****
*****


In [32]:
for i in range(5):
    for j in range(i+1):
        print("*", end="")
    print()  # Move to the next line after printing stars

*
**
***
****
*****
